//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSchoolProjectEntities1 : DbContext
    {
        public DbSchoolProjectEntities1()
            : base("name=DbSchoolProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAccount> TblAccount { get; set; }
        public virtual DbSet<TblAnnouncement> TblAnnouncement { get; set; }
        public virtual DbSet<TblAssignment> TblAssignment { get; set; }
        public virtual DbSet<TblCourses> TblCourses { get; set; }
        public virtual DbSet<TblGrade> TblGrade { get; set; }
        public virtual DbSet<TblRegistrar> TblRegistrar { get; set; }
        public virtual DbSet<TblStudent> TblStudent { get; set; }
        public virtual DbSet<TblTeacher> TblTeacher { get; set; }
    }
}
