//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAssignment
    {
        public int ID { get; set; }
        public string Course { get; set; }
        public Nullable<int> Section { get; set; }
        public string Content { get; set; }
        public string SentBy { get; set; }
    }
}
