//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCourses
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CourseCode { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<int> Quota { get; set; }
        public Nullable<int> ActiveStudents { get; set; }
        public Nullable<bool> IsOpenRegistration { get; set; }
        public string Department { get; set; }
    }
}
